### ISSUE TITLE
Active Record associations between engines Question

### ISSUE THREAD

**Issue by DangerDawson** [shageman/sportsball#1]
First of all thanks for sharing your approach with engines, we were doing something similar although you have helped solidify a couple of things we were doing.

I have a question about associations, below you have 2 models (Teams::Team and Games::Game ) and you have the association from Game to Team in place ( which makes sense as there is a dependency in your gemspec Games requires Teams ). But how would you suggest providing the other relationship? 

My thoughts would be to use a refinement in the Games engine that decorates the Teams::Team model with:

```
has_many :games class_name: 'Games::Game'
```

your thoughts?

Models in question

```
module Teams
  class Team < ActiveRecord::Base
    validates :name, presence: true
  end
end
```

```
module Games
  class Game < ActiveRecord::Base
    validates :date, :location, :first_team, :second_team, :winning_team,
              :first_team_score, :second_team_score, presence: true
    belongs_to :first_team, class_name: 'Teams::Team'
    belongs_to :second_team, class_name: 'Teams::Team'
  end
end
```

**Comment by simo163** [comment]
@DangerDawson I think in this case Teams must require a dependency Games as well so that you can use it.

**Comment by shageman** [comment]
Hey all,

Sorry I missed this discussion. My notification settings were screwed up for this repo 👎 

It is _feature_ not a "bug" that you can only refer to classes in one direction with components. This is what prevents cyclic dependencies. That in turn forces you to structure your domain in a way that makes sense for your use case while ensuring that you don't ramp up lots of incidental complexity. So, **first option** is: either `Games` refers to `Teams` or `Teams` refers to `Games`, you can't have both.

**Second option**: You could create a component "above" `Teams` and `Games` that depends on both of them where you create and manage the join. This does not give you exactly what you are looking for, but still one place in which you can calculate/return `Games` in the context of a `Team` and `Teams` in the context of a `Game`.

If for your domain (**third answer**), you decide that `Games` and `Teams` are so connected that they should both be able to refer to each other directly, as you describe. To do this, move them into the same component.
