### ISSUE TITLE
deploying cbra with web_container 

### ISSUE THREAD

**Issue by mgharbik** [shageman/sportsball#3]
Hi,

with Capistrano I am trying to deploy a cbra project which uses the new structure that contains the main app in the web_container directory. Could you give some tips about the configuration? we're having issues with bundler in the releases.

With kind regards,

**Comment by shageman** [comment]
Hi Mohammed,

I am sorry I dropped the ball on your question. I was too focused on my work over at https://github.com/shageman/cbra_book_code. More importantly, I screwed up my github notifications and never saw your message.

Please let me know if there is anything you would still like to know or discuss about this topic!
